### ISSUE TITLE
global game-state object

### ISSUE THREAD

**Issue by aescarcha** [breuerfelix/king-bot#33]
I've been thinking about how the application is built for a while, and it looks scripty. I think future features may be easier to implement if and easier to configure by saving the global status of the game and then reacting to it, it would require a lot of Objects like Village, resource fields, buildings... but it may be good to keep it in mind for the future. Any thoughts?

**Comment by scriptworld-git** [comment]
well my first implementation of the bot was like that... I had world, village and slot objects.  
after several features these classes grew a lot, it was a mess to understand this structure and it was also a mess to implement new features for other people than me.  
this is why I thought okay, every big feature gets one file. so if you are new to the project and wanna see what farming is doing, you just have to look up and search in one file.  
I hoped that its also was easier to fix some stuff like that.  

to save the game state I thought about a struct (since python doesn't have structs, maybe just a class).
this class represents the state of the game. since you can only be logged into one game world, this class can be a singleton. every function got easy access to this game state object and can react / modify it.  
this singleton ONLY contains game state and no functions (but only some functions to reload the state).

what do you think about that approach?
